markdown: rdiscount
permalink: /:title/
url: http://shixy.github.com
name: shixy's blog
author: shixy
qq: 35518781
email: walker.shixy@gmail.com
duoshuo: vycool
beian: 
cnzz: 1000218179
weibo: 1885569900
github: shixy
pygments: true
safe: true
paginate: 20
about: "不会写博客"
